# Generated by Django 3.2 on 2021-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('black', 'Black'), ('blue', 'Blue')], default='black', max_length=20),
        ),
    ]
